language: java
sudo: false
jdk:
  - openjdk7
  - oraclejdk8
env:
  - HV_VERSION=4.3.1.Final
  - HV_VERSION=5.0.3.Final
  - HV_VERSION=5.1.3.Final
  - HV_VERSION=5.2.1.Final
script:
  - "mvn verify -B -Ptest-different-hv-version -Dhibernate-validator.version.test=${HV_VERSION}"
after_success:
  - 'mvn jacoco:report coveralls:jacoco'
