sudo: false
language: java
jdk:
  - openjdk7
  - oraclejdk8
env:
  - HV_VERSION=4.3.1.Final
  - HV_VERSION=5.0.3.Final
  - HV_VERSION=5.1.3.Final
  - HV_VERSION=5.2.3.Final

# Cache local Maven repository
cache:
  directories:
    - $HOME/.m2
before_cache:
  - rm -Rf ~/.m2/repository/cz/jirutka/validator/validator-collection

install:
  - mvn install -Ptest-different-hv-version -Dhibernate-validator.version.test=${HV_VERSION} -DskipTests=true --batch-mode
script:
  - mvn verify -Ptest-different-hv-version -Dhibernate-validator.version.test=${HV_VERSION} --batch-mode
after_success:
  - mvn jacoco:report coveralls:report
