language: java
sudo: false
jdk:
  - openjdk7
  - oraclejdk8
env:
  - HV_VERSION=4.3.1.Final
  - HV_VERSION=5.0.3.Final
  - HV_VERSION=5.1.1.Final
script:
  - "mvn verify -B -Ptest-different-hv-version"
after_success:
  - 'mvn jacoco:report coveralls:jacoco'
